import React, { useState, useEffect } from "react";
import { Loader, Card, FormField } from "../components";

const RenderCards = ({ data, title }) => {
  if (data?.lenght > 0) {
    //try data.lenght>0 later
    return data.map((post) => {
      //map through each post
      <Card key={post._id} {...post} />; //spreading out all post data to each individual card
    });
  }

  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false); //at the start the loading will be set to false
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setsearchText] = useState("");

  //max-w-7xl will be a max - width of about 80 rem
  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[2rem]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[1.2rem] max-w-[500px]">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>
      <div className="mt-16">
        <FormField />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && ( //if there's any text it will execute
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing results for{" "}
                <span className="text-[#222328]">{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 gird-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={[]} // we will pass by an array of data later
                  title="No search results found"
                />
              ) : (
                <RenderCards
                  data={[]} // we will pass by an array of data later
                  title="No posts found"
                />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
